# Prometheus Configuration for MLB Data Service
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    service: 'mlb-data-service'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # MLB Data Service
  - job_name: 'mlb-data-service'
    static_configs:
      - targets: ['mlb-data-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    
  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    
  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    
  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s

# Recording rules for common queries
recording_rules:
  - name: mlb_service_rules
    rules:
      - record: mlb:request_rate_5m
        expr: rate(http_requests_total[5m])
        
      - record: mlb:error_rate_5m
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])
        
      - record: mlb:response_time_95th
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))
        
      - record: mlb:memory_usage_percent
        expr: (process_resident_memory_bytes / 1024 / 1024) / 2048 * 100
        
      - record: mlb:cpu_usage_percent
        expr: rate(process_cpu_seconds_total[5m]) * 100