# Promtail Configuration for MLB Data Service
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # MLB Data Service logs
  - job_name: mlb-data-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: mlb-data-service
          service: mlb-data-service
          environment: production
          __path__: /var/log/mlb-service/*.log

    # Parse JSON logs
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            logger: logger
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          logger:

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          service: system
          environment: production
          __path__: /var/log/syslog

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+\s+\d+\s+\d+:\d+:\d+)\s+(?P<host>\S+)\s+(?P<process>\S+):\s+(?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: 'Jan 02 15:04:05'
      - labels:
          host:
          process:

  # Docker container logs  
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          service: docker
          environment: production
          __path__: /var/log/docker/*.log

    pipeline_stages:
      - json:
          expressions:
            container_name: attrs.name
            log: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          container_name:
          stream:

  # PostgreSQL logs (if available)
  - job_name: postgres
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgres
          service: database
          environment: production
          __path__: /var/log/postgresql/*.log

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}.\d{3})\s+\w+\s+\[(?P<pid>\d+)\]\s+(?P<level>\w+):\s+(?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000'
      - labels:
          level:
          pid: